### ISSUE TITLE
Icdrama 1.1.2

### ISSUE THREAD

**Issue by kokoronikui** [cthlo/plugin.video.icdrama#1]
Hi,  the latest update has fixed the episode list issue in a drama with many episodes where ep1 onwards isn't listed but it has broken the page selection only in the hk dramas section where only the first page of dramas is being listed despite the page chosen

**Comment by cthlo** [comment]
Thanks! It happened due to an unexpected change on Icdrama's site. And they have fixed the site. So no fix is required.
